name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if dev branch needs update
        id: check
        run: |
          git checkout dev
          git pull origin dev

          # 檢查 dev 分支是否已經包含 main 分支的最新 commit
          MAIN_COMMIT=$(git rev-parse origin/main)
          DEV_COMMIT=$(git rev-parse HEAD)

          # 檢查 main 的 commit 是否已經在 dev 分支中
          if git merge-base --is-ancestor $MAIN_COMMIT HEAD; then
            echo "Dev branch is already up to date with main"
            echo "needs_update=false" >> $GITHUB_OUTPUT
          else
            echo "Dev branch needs update"
            echo "needs_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Sync changes to dev branch
        if: steps.check.outputs.needs_update == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 使用 fast-forward merge 或 rebase 來避免不必要的 merge commits
          if git merge origin/main --ff-only; then
            echo "Fast-forward merge successful"
          else
            echo "Fast-forward not possible, using rebase"
            git rebase origin/main
          fi

          git push origin dev
