name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local advice.diverging false

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if dev branch exists
        id: check_dev
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/dev; then
            echo "dev_exists=true" >> $GITHUB_OUTPUT
          else
            echo "dev_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create dev branch if it doesn't exist
        if: steps.check_dev.outputs.dev_exists == 'false'
        run: |
          git checkout -b dev
          git push origin dev
          echo "Created new dev branch"

      - name: Sync changes to dev branch
        if: steps.check_dev.outputs.dev_exists == 'true'
        run: |
          # Switch to dev branch
          git checkout dev
          
          # Reset dev branch to match main branch exactly
          git reset --hard origin/main
          
          # Force push to update dev branch
          git push --force-with-lease origin dev
          
          echo "Successfully synced dev branch with main"

      - name: Verify sync
        run: |
          git checkout dev
          MAIN_COMMIT=$(git rev-parse origin/main)
          DEV_COMMIT=$(git rev-parse HEAD)
          
          if [ "$MAIN_COMMIT" = "$DEV_COMMIT" ]; then
            echo "✅ Dev branch is now in sync with main"
          else
            echo "❌ Sync failed - commits don't match"
            exit 1
          fi
