name: Sync Main to Dev

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0  # 取得所有 commit

      - name: Fetch all branches
        run: git fetch --all

      - name: Push changes to dev branch
        run: |
          # 如果是 PR merge commit，則跳過
          if git log -1 --pretty=%B | grep -q "Merge pull request"; then
            echo "Skip: This is a PR merge commit."
            exit 0
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout dev
          git merge main --no-ff -m "Sync changes from main to dev"
          git push origin dev