name: Build Python Package

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Build application
        run: |
          uv build

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-artifact-${{ matrix.python-version }}-${{ github.run_id }}
          path: dist/*.whl
